### ISSUE TITLE
macOS Safari で Favicon が正常に表示されない

### ISSUE THREAD

**Issue by forestk** [ArcCosine/nyaan#5]
macOS Safari で Favicon が正常に表示されない現象が発生している。
<img width="151" alt="safari favicon" src="https://user-images.githubusercontent.com/1407202/89701258-f9935100-d96f-11ea-92e1-8c45bbc15b39.png">

## 原因
[safari-pinned-tab.svg](https://nyaan.work/safari-pinned-tab.svg) が優先されて適用されるため。

## 対応策
次の2つのどちらか。
1. [safari-pinned-tab.svg](https://nyaan.work/safari-pinned-tab.svg) を Favicon と同じ形状にする
2. [safari-pinned-tab.svg](https://nyaan.work/safari-pinned-tab.svg) を使用しないようにする（Safari でピン留めタブを行った際に影響するが、最悪 Favicon が表示されるはず）

**Comment by ArcCosine** [comment]
https://github.com/ArcCosine/nyaan/commit/39315bb6fe9952d791f37b43a50f4734e3022951

Compatible with the above versions.
Thanks for telling me the problem.


上記コミットで、safari-pinned-tab.svgを削除しました。
不具合をご連絡いただきありがとうございます。
